version: 1.0.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/AuditLogger/AL.Api/AL.Api.csproj --verbosity m
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_aspnet_core: true
  parallel: true
  verbosity: minimal